- name: encode bind credentials
  asb_encode_binding:
    fields:
      DB_TYPE: "mysql"
      DB_PASSWORD: "{{ MasterUserPassword }}"
      DB_NAME: "{{ DBName }}"
      DB_HOST: "{{ rds_endpoint_address }}"
      DB_PORT: "{{ PortNumber }}"
      DB_USER: "{{ MasterUsername }}"
